name: .NET

on:
  pull_request:
    branches: [ prod ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      env:
        NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'

    - name: Restore dependencies
      run: dotnet restore TasksOnTimeStandard.sln

    - name: Build
      run: dotnet build DistributedTasksOnTime.sln --configuration Release

    - name: Test
      run: dotnet test src\TasksOnTimeCore.Tests\TasksOnTimeCore.Tests.csproj -c Release --no-build --verbosity normal

    - name: Pack TasksOnTimeCore
      run: dotnet pack --no-build --configuration Release ${{github.workspace}}\src\TasksOnTimeCore\TasksOnTimeCore.csproj --output .

    - name: Push Nuget
      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.nuget}} --skip-duplicate

    - name: Publish TasksOnTimeCore to nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: ${{github.workspace}}\src\TasksOnTimeCore\TasksOnTimeCore.csproj
        PACKAGE_NAME: TasksOnTimeCore
        NUGET_SOURCE: https://api.nuget.org
        NUGET_KEY: ${{secrets.nuget}}

    - name: Publish TasksOnTimeCore.Scheduling to nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: ${{github.workspace}}\src\TasksOnTimeCore.Scheduling\TasksOnTimeCore.Scheduling.csproj
        PACKAGE_NAME: TasksOnTimeCore.Scheduling
        NUGET_SOURCE: https://api.nuget.org
        NUGET_KEY: ${{secrets.nuget}}

    - name: Publish TasksOnTimeCore.Client to nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: ${{github.workspace}}\src\DistributedTasksOnTime.Client\DistributedTasksOnTime.Client.csproj
        PACKAGE_NAME: DistributedTasksOnTime.Client
        NUGET_SOURCE: https://api.nuget.org
        NUGET_KEY: ${{secrets.nuget}}

    - name: Publish DistributedTasksOnTime.BlazorComponent to nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: ${{github.workspace}}\src\DistributedTasksOnTime.BlazorComponent\DistributedTasksOnTime.BlazorComponent.csproj
        PACKAGE_NAME: DistributedTasksOnTime.Client
        NUGET_SOURCE: https://api.nuget.org
        NUGET_KEY: ${{secrets.nuget}}
