name: .NET

on:
  pull_request:
    branches: [ prod ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x
      env:
        NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'

    - name: Restore dependencies
      run: dotnet restore TasksOnTimeStandard.sln

    - name: Build
      run: dotnet build DistributedTasksOnTime.sln --configuration Release

    #- name: Test
    #  run: dotnet test src\TasksOnTimeCore.Tests\TasksOnTimeCore.Tests.csproj -c Release --no-build --verbosity normal

    - name: Pack TasksOnTimeCore
      run: dotnet pack --no-build --configuration Release ${{github.workspace}}\src\TasksOnTimeCore\TasksOnTimeCore.csproj --output .

    - name: Pack TasksOnTimeCore.Scheduling
      run: dotnet pack --no-build --configuration Release ${{github.workspace}}\src\TasksOnTimeCore.Scheduling\TasksOnTimeCore.Scheduling.csproj --output .

    - name: Pack DistributedTasksOnTime.Client
      run: dotnet pack --no-build --configuration Release ${{github.workspace}}\src\DistributedTasksOnTime.Client\DistributedTasksOnTime.Client.csproj --output .

    - name: Pack DistributedTasksOnTime.BlazorComponent
      run: dotnet pack --no-build --configuration Release ${{github.workspace}}\src\DistributedTasksOnTime.BlazorComponent\DistributedTasksOnTime.BlazorComponent.csproj --output .

    - name: Pack DistributedTasksOnTime.JsonFilePersistence
      run: dotnet pack --no-build --configuration Release ${{github.workspace}}\src\DistributedTasksOnTime.JsonFilePersistence\DistributedTasksOnTime.JsonFilePersistence.csproj --output .

    - name: Pack DistributedTasksOnTime.SqlitePersistence
      run: dotnet pack --no-build --configuration Release ${{github.workspace}}\src\DistributedTasksOnTime.SqlitePersistence\DistributedTasksOnTime.SqlitePersistence.csproj --output .

    - name: Push Nuget
      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.nuget}} --skip-duplicate

